// The overhaul candidates (cands-*.ts) Adam has passed by ear, each with his verdict: id -> why it replaced what
// shipped. recipes.ts puts each in its id's place. Written by scripts/sfx/approve.py; empty until Adam listens.
export const APPROVED: Readonly<Record<string, string>> = {
  "airHorn": "Adam, 30 Sept 2026, after the old-then-new files 01-98: \"Let's just go with yes for all\"",
  "amb-boardwalk-nights": "Adam, 30 Sept 2026, after the old-then-new files 01-98: \"Let's just go with yes for all\"",
  "amb-canyon-rush": "Adam, 30 Sept 2026, after the old-then-new files 01-98: \"Let's just go with yes for all\"",
  "amb-frostbite-pass": "Adam, 30 Sept 2026, after the old-then-new files 01-98: \"Let's just go with yes for all\"",
  "amb-harbour-loop": "Adam, 30 Sept 2026, after the old-then-new files 01-98: \"Let's just go with yes for all\"",
  "amb-meadow-run": "Adam, 30 Sept 2026, after the old-then-new files 01-98: \"Let's just go with yes for all\"",
  "amb-skyline-circuit": "Adam, 30 Sept 2026, after the old-then-new files 01-98: \"Let's just go with yes for all\"",
  "anchor": "Adam, 30 Sept 2026, after the old-then-new files 01-98: \"Let's just go with yes for all\"",
  "balloon": "Adam, 30 Sept 2026, after the old-then-new files 01-98: \"Let's just go with yes for all\"",
  "blocked": "Adam, 30 Sept 2026, after the old-then-new files 01-98: \"Let's just go with yes for all\"",
  "boing": "Adam, 30 Sept 2026, after the old-then-new files 01-98: \"Let's just go with yes for all\"",
  "boost1": "Adam, 30 Sept 2026, after the old-then-new files 01-98: \"Let's just go with yes for all\"",
  "boost2": "Adam, 30 Sept 2026, after the old-then-new files 01-98: \"Let's just go with yes for all\"",
  "boost3": "Adam, 30 Sept 2026, after the old-then-new files 01-98: \"Let's just go with yes for all\"",
  "boostPad": "Adam, 30 Sept 2026, after the old-then-new files 01-98: \"Let's just go with yes for all\"",
  "boostStart": "Adam, 30 Sept 2026, after the old-then-new files 01-98: \"Let's just go with yes for all\"",
  "boostTrick": "Adam, 30 Sept 2026, after the old-then-new files 01-98: \"Let's just go with yes for all\"",
  "bounce": "Adam, 30 Sept 2026, after the old-then-new files 01-98: \"Let's just go with yes for all\"",
  "bump": "Adam, 30 Sept 2026, after the old-then-new files 01-98: \"Let's just go with yes for all\"",
  "claw": "Adam, 30 Sept 2026, after the old-then-new files 01-98: \"Let's just go with yes for all\"",
  "clawDrop": "Adam, 30 Sept 2026, after the old-then-new files 01-98: \"Let's just go with yes for all\"",
  "coin": "Adam, 30 Sept 2026, after the old-then-new files 01-98: \"Let's just go with yes for all\"",
  "count": "Adam, 30 Sept 2026, after the old-then-new files 01-98: \"Let's just go with yes for all\"",
  "crabClack": "Adam, 30 Sept 2026, after the old-then-new files 01-98: \"Let's just go with yes for all\"",
  "denied": "Adam, 30 Sept 2026, after the old-then-new files 01-98: \"Let's just go with yes for all\"",
  "drift": "Adam, 30 Sept 2026, after the old-then-new files 01-98: \"Let's just go with yes for all\"",
  "drop": "Adam, 30 Sept 2026, after the old-then-new files 01-98: \"Let's just go with yes for all\"",
  "engine-high": "Adam, 30 Sept 2026, after the old-then-new files 01-98: \"Let's just go with yes for all\"",
  "engine-idle": "Adam, 30 Sept 2026, after the old-then-new files 01-98: \"Let's just go with yes for all\"",
  "engine-mid": "Adam, 30 Sept 2026, after the old-then-new files 01-98: \"Let's just go with yes for all\"",
  "finalLap": "Adam, 30 Sept 2026, after the old-then-new files 01-98: \"Let's just go with yes for all\"",
  "finish": "Adam, 30 Sept 2026, after the old-then-new files 01-98: \"Let's just go with yes for all\"",
  "finishLow": "Adam, 30 Sept 2026, after the old-then-new files 01-98: \"Let's just go with yes for all\"",
  "fizz": "Adam, 30 Sept 2026, after the old-then-new files 01-98: \"Let's just go with yes for all\"",
  "fog": "Adam, 30 Sept 2026, after the old-then-new files 01-98: \"Let's just go with yes for all\"",
  "gainPlace": "Adam, 30 Sept 2026, after the old-then-new files 01-98: \"Let's just go with yes for all\"",
  "geyser": "Adam, 30 Sept 2026, after the old-then-new files 01-98: \"Let's just go with yes for all\"",
  "go": "Adam, 30 Sept 2026, after the old-then-new files 01-98: \"Let's just go with yes for all\"",
  "hit": "Adam, 30 Sept 2026, after the old-then-new files 01-98: \"Let's just go with yes for all\"",
  "hitConfirm": "Adam, 30 Sept 2026, after the old-then-new files 01-98: \"Let's just go with yes for all\"",
  "honk": "Adam, 30 Sept 2026, after the old-then-new files 01-98: \"Let's just go with yes for all\"",
  "hop": "Adam, 30 Sept 2026, after the old-then-new files 01-98: \"Let's just go with yes for all\"",
  "horn:boulder": "Adam, 30 Sept 2026, after the old-then-new files 01-98: \"Let's just go with yes for all\"",
  "horn:gus": "Adam, 30 Sept 2026, after the old-then-new files 01-98: \"Let's just go with yes for all\"",
  "horn:juniper": "Adam, 30 Sept 2026, after the old-then-new files 01-98: \"Let's just go with yes for all\"",
  "horn:momo": "Adam, 30 Sept 2026, after the old-then-new files 01-98: \"Let's just go with yes for all\"",
  "horn:nova": "Adam, 30 Sept 2026, after the old-then-new files 01-98: \"Let's just go with yes for all\"",
  "horn:otto": "Adam, 30 Sept 2026, after the old-then-new files 01-98: \"Let's just go with yes for all\"",
  "horn:pip": "Adam, 30 Sept 2026, after the old-then-new files 01-98: \"Let's just go with yes for all\"",
  "horn:sprocket": "Adam, 30 Sept 2026, after the old-then-new files 01-98: \"Let's just go with yes for all\"",
  "itemReady": "Adam, 30 Sept 2026, after the old-then-new files 01-98: \"Let's just go with yes for all\"",
  "kite": "Adam, 30 Sept 2026, after the old-then-new files 01-98: \"Let's just go with yes for all\"",
  "koOut": "Adam, 30 Sept 2026, after the old-then-new files 01-98: \"Let's just go with yes for all\"",
  "koSafe": "Adam, 30 Sept 2026, after the old-then-new files 01-98: \"Let's just go with yes for all\"",
  "krakenRise": "Adam, 30 Sept 2026, after the old-then-new files 01-98: \"Let's just go with yes for all\"",
  "krakenSlam": "Adam, 30 Sept 2026, after the old-then-new files 01-98: \"Let's just go with yes for all\"",
  "land": "Adam, 30 Sept 2026, after the old-then-new files 01-98: \"Let's just go with yes for all\"",
  "lap": "Adam, 30 Sept 2026, after the old-then-new files 01-98: \"Let's just go with yes for all\"",
  "loop": "Adam, 30 Sept 2026, after the old-then-new files 01-98: \"Let's just go with yes for all\"",
  "losePlace": "Adam, 30 Sept 2026, after the old-then-new files 01-98: \"Let's just go with yes for all\"",
  "mouse": "Adam, 30 Sept 2026, after the old-then-new files 01-98: \"Let's just go with yes for all\"",
  "offroad": "Adam, 30 Sept 2026, after the old-then-new files 01-98: \"Let's just go with yes for all\"",
  "offroad-sand": "Adam, 30 Sept 2026, after the old-then-new files 01-98: \"Let's just go with yes for all\"",
  "offroad-snow": "Adam, 30 Sept 2026, after the old-then-new files 01-98: \"Let's just go with yes for all\"",
  "pop": "Adam, 30 Sept 2026, after the old-then-new files 01-98: \"Let's just go with yes for all\"",
  "rail-grind": "Adam, 30 Sept 2026, after the old-then-new files 01-98: \"Let's just go with yes for all\"",
  "respawn": "Adam, 30 Sept 2026, after the old-then-new files 01-98: \"Let's just go with yes for all\"",
  "road-ice": "Adam, 30 Sept 2026, after the old-then-new files 01-98: \"Let's just go with yes for all\"",
  "road-wood": "Adam, 30 Sept 2026, after the old-then-new files 01-98: \"Let's just go with yes for all\"",
  "roar": "Adam, 30 Sept 2026, after the old-then-new files 01-98: \"Let's just go with yes for all\"",
  "rouletteTick": "Adam, 30 Sept 2026, after the old-then-new files 01-98: \"Let's just go with yes for all\"",
  "shieldEnd": "Adam, 30 Sept 2026, after the old-then-new files 01-98: \"Let's just go with yes for all\"",
  "shieldPop": "Adam, 30 Sept 2026, after the old-then-new files 01-98: \"Let's just go with yes for all\"",
  "shieldUp": "Adam, 30 Sept 2026, after the old-then-new files 01-98: \"Let's just go with yes for all\"",
  "shift": "Adam, 30 Sept 2026, after the old-then-new files 01-98: \"Let's just go with yes for all\"",
  "slam": "Adam, 30 Sept 2026, after the old-then-new files 01-98: \"Let's just go with yes for all\"",
  "slingshot": "Adam, 30 Sept 2026, after the old-then-new files 01-98: \"Let's just go with yes for all\"",
  "slipstream": "Adam, 30 Sept 2026, after the old-then-new files 01-98: \"Let's just go with yes for all\"",
  "snowThud": "Adam, 30 Sept 2026, after the old-then-new files 01-98: \"Let's just go with yes for all\"",
  "sparks": "Adam, 30 Sept 2026, after the old-then-new files 01-98: \"Let's just go with yes for all\"",
  "spin": "Adam, 30 Sept 2026, after the old-then-new files 01-98: \"Let's just go with yes for all\"",
  "steamVent": "Adam, 30 Sept 2026, after the old-then-new files 01-98: \"Let's just go with yes for all\"",
  "stomp": "Adam, 30 Sept 2026, after the old-then-new files 01-98: \"Let's just go with yes for all\"",
  "strike": "Adam, 30 Sept 2026, after the old-then-new files 01-98: \"Let's just go with yes for all\"",
  "strikeRoll": "Adam, 30 Sept 2026, after the old-then-new files 01-98: \"Let's just go with yes for all\"",
  "tailSlap": "Adam, 30 Sept 2026, after the old-then-new files 01-98: \"Let's just go with yes for all\"",
  "throw": "Adam, 30 Sept 2026, after the old-then-new files 01-98: \"Let's just go with yes for all\"",
  "tierUp": "Adam, 30 Sept 2026, after the old-then-new files 01-98: \"Let's just go with yes for all\"",
  "tierUp2": "Adam, 30 Sept 2026, after the old-then-new files 01-98: \"Let's just go with yes for all\"",
  "tierUp3": "Adam, 30 Sept 2026, after the old-then-new files 01-98: \"Let's just go with yes for all\"",
  "trail": "Adam, 30 Sept 2026, after the old-then-new files 01-98: \"Let's just go with yes for all\"",
  "trick": "Adam, 30 Sept 2026, after the old-then-new files 01-98: \"Let's just go with yes for all\"",
  "uiBack": "Adam, 30 Sept 2026, after the old-then-new files 01-98: \"Let's just go with yes for all\"",
  "uiConfirm": "Adam, 30 Sept 2026, after the old-then-new files 01-98: \"Let's just go with yes for all\"",
  "uiMove": "Adam, 30 Sept 2026, after the old-then-new files 01-98: \"Let's just go with yes for all\"",
  "ventWarn": "Adam, 30 Sept 2026, after the old-then-new files 01-98: \"Let's just go with yes for all\"",
  "wall": "Adam, 30 Sept 2026, after the old-then-new files 01-98: \"Let's just go with yes for all\"",
  "whaleSong": "Adam, 30 Sept 2026, after the old-then-new files 01-98: \"Let's just go with yes for all\"",
  "wrongWay": "Adam, 30 Sept 2026, after the old-then-new files 01-98: \"Let's just go with yes for all\"",
  "yelp:boulder": "Adam, 30 Sept 2026: \"Let's just go with yes for all\" (the yelps with the rest, not heard alone: until now a racer with hit lines never yelped)",
  "yelp:gus": "Adam, 30 Sept 2026: \"Let's just go with yes for all\" (the yelps with the rest, not heard alone: until now a racer with hit lines never yelped)",
  "yelp:juniper": "Adam, 30 Sept 2026: \"Let's just go with yes for all\" (the yelps with the rest, not heard alone: until now a racer with hit lines never yelped)",
  "yelp:momo": "Adam, 30 Sept 2026: \"Let's just go with yes for all\" (the yelps with the rest, not heard alone: until now a racer with hit lines never yelped)",
  "yelp:nova": "Adam, 30 Sept 2026: \"Let's just go with yes for all\" (the yelps with the rest, not heard alone: until now a racer with hit lines never yelped)",
  "yelp:otto": "Adam, 30 Sept 2026: \"Let's just go with yes for all\" (the yelps with the rest, not heard alone: until now a racer with hit lines never yelped)",
  "yelp:pip": "Adam, 30 Sept 2026: \"Let's just go with yes for all\" (the yelps with the rest, not heard alone: until now a racer with hit lines never yelped)",
  "yelp:sprocket": "Adam, 30 Sept 2026: \"Let's just go with yes for all\" (the yelps with the rest, not heard alone: until now a racer with hit lines never yelped)",
  "yetiThrow": "Adam, 30 Sept 2026, after the old-then-new files 01-98: \"Let's just go with yes for all\"",
};
