// submit-score: the only way a score reaches the database (docs/sops/backend-leaderboard.md).
// Order: CORS (the game's own pages only) → size → atomic rate limit per hashed client (IPv6 by
// /64; fails closed) → the body, capped in size and time → field rules → re-simulate the input log
// with the real game code → insert the canonical log with the service role. The stored time is
// always the replay's; one drive is one row.
// core.js is generated by `npm run build:function`; never edit it by hand.
import { CLIENT_VERSION, MAX_LOG_BYTES, TRACKS, TRACK_IDS, checkSubmission, dailySeed, ipBucket, verifyRun } from './core.js';

const SUPABASE_URL = Deno.env.get('SUPABASE_URL') ?? '';
const SERVICE_KEY = Deno.env.get('SUPABASE_SERVICE_ROLE_KEY') ?? '';
/** the public key: get_leaderboard is granted to anon (the board players see), not to the service role */
const ANON_KEY = Deno.env.get('SUPABASE_ANON_KEY') ?? '';
const LIMIT_PER_MINUTE = 10;
/** accepted runs per client per day: plenty for a person, a ceiling for a flood */
const LIMIT_PER_DAY = 60;
/** names one client may hold on one board: room for a shared home, not for a flood of copies (the trigger in migration 20260925000001 holds the same 3) */
const NAMES_PER_BOARD = 3;
const MAX_BODY = MAX_LOG_BYTES + 4096;
/**
 * The whole body must arrive within this. A second line: measured 24 Sept 2026, Supabase's gateway
 * holds a stalled or trickled body itself (a byte every 10 s kept it waiting past a minute) and the
 * function never started (no rate-limit row); should that change, a trickle cannot hold the worker.
 */
const READ_MS = 15_000;

/**
 * Pages that may post from a browser: the live site, and the dev server on this machine. Any other
 * page is refused before it costs a rate-limit slot (red-team 24 Sept 2026): with '*', a busy page
 * elsewhere could make each visitor's browser post, one IP apiece, past the per-client limits.
 * A request with no Origin (curl, a script) is no browser borrowing a visitor; the limits hold it.
 * Add the Vercel address here when the game moves there.
 */
const ORIGINS = ['https://adamwebsiteformula.github.io'];
const allowedOrigin = (o: string | null): boolean => o === null || ORIGINS.includes(o) || /^http:\/\/(localhost|127\.0\.0\.1)(:\d{1,5})?$/.test(o);

const cors = (origin: string | null): Record<string, string> => ({
  ...(origin && allowedOrigin(origin) ? { 'Access-Control-Allow-Origin': origin } : {}),
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
  'Access-Control-Allow-Methods': 'POST, OPTIONS',
  'Access-Control-Max-Age': '7200',
  Vary: 'Origin',
});

const jsonFor = (status: number, body: unknown, origin: string | null) =>
  new Response(JSON.stringify(body), { status, headers: { ...cors(origin), 'Content-Type': 'application/json' } });

const rest = (path: string, init: RequestInit = {}) =>
  fetch(`${SUPABASE_URL}/rest/v1/${path}`, {
    ...init,
    headers: { apikey: SERVICE_KEY, Authorization: `Bearer ${SERVICE_KEY}`, 'Content-Type': 'application/json', ...(init.headers ?? {}) },
  });

async function sha256(text: string): Promise<string> {
  const d = await crypto.subtle.digest('SHA-256', new TextEncoder().encode(text));
  return [...new Uint8Array(d)].map((b) => b.toString(16).padStart(2, '0')).join('');
}

function clientIp(req: Request): string {
  return req.headers.get('cf-connecting-ip') ?? req.headers.get('x-real-ip') ?? req.headers.get('x-forwarded-for')?.split(',')[0]?.trim() ?? 'unknown';
}

/**
 * One atomic step in the database (take_submit_slot): under both limits it records this attempt
 * and says true. Null when the database could not answer: the caller then refuses (fails closed).
 */
async function takeSlot(ipHash: string): Promise<boolean | null> {
  const r = await rest('rpc/take_submit_slot', {
    method: 'POST', body: JSON.stringify({ p_ip_hash: ipHash, p_per_minute: LIMIT_PER_MINUTE, p_per_day: LIMIT_PER_DAY }),
  }).catch(() => null);
  if (!r?.ok) return null;
  return (await r.json().catch(() => null)) === true;
}

/**
 * The body as text; null past `max` bytes, 'slow' when it has not all arrived within `ms`. Reading
 * stops either way, so neither a chunked upload with no length nor a trickle can hold memory or the worker.
 */
async function readCapped(req: Request, max: number, ms = READ_MS): Promise<string | null | 'slow'> {
  if (!req.body) return '';
  const reader = req.body.getReader();
  let timer: ReturnType<typeof setTimeout> | undefined;
  const late = new Promise<'slow'>((r) => { timer = setTimeout(() => r('slow'), ms); });
  try {
    const parts: Uint8Array[] = [];
    let size = 0;
    for (;;) {
      const next = await Promise.race([reader.read(), late]);
      if (next === 'slow') { reader.cancel().catch(() => {}); return 'slow'; }
      if (next.done) break;
      size += next.value.byteLength;
      if (size > max) { await reader.cancel().catch(() => {}); return null; }
      parts.push(next.value);
    }
    const all = new Uint8Array(size);
    let o = 0;
    for (const p of parts) { all.set(p, o); o += p.byteLength; }
    return new TextDecoder().decode(all);
  } finally {
    clearTimeout(timer);
  }
}

Deno.serve(async (req) => {
  const origin = req.headers.get('origin');
  const json = (status: number, body: unknown) => jsonFor(status, body, origin);
  if (!allowedOrigin(origin)) return req.method === 'OPTIONS' ? new Response(null, { status: 403, headers: cors(origin) }) : json(403, { error: 'scores are posted from the game only' });
  if (req.method === 'OPTIONS') return new Response('ok', { headers: cors(origin) });
  if (req.method !== 'POST') return json(405, { error: 'POST only' });
  if (!SUPABASE_URL || !SERVICE_KEY) return json(500, { error: 'server not configured' });

  // refuse an oversized body before reading it
  if (Number(req.headers.get('content-length') ?? '0') > MAX_BODY) return json(413, { error: 'payload too large' });

  // salted so the stored hash cannot be reversed with a table of IPs; IPv6 counts by its /64
  const ipHash = await sha256(`${ipBucket(clientIp(req))}|${SERVICE_KEY.slice(-24)}`);
  const slot = await takeSlot(ipHash);
  if (slot === null) return json(503, { error: 'the leaderboard is busy: try again soon' });
  if (!slot) return json(429, { error: 'too many submissions: wait a minute' });

  const text = await readCapped(req, MAX_BODY);
  if (text === 'slow') return json(408, { error: 'the upload took too long' });
  if (text === null) return json(413, { error: 'payload too large' });
  let body: Record<string, unknown>;
  try { body = JSON.parse(text); } catch { return json(400, { error: 'body must be JSON' }); }

  const problem = checkSubmission(body, TRACK_IDS, dailySeed());
  if (problem) return json(400, { error: problem });

  const mode = body.mode as 'timeTrial' | 'daily';
  const seed = mode === 'daily' ? (body.dailySeed as number) : 0;
  const name = (body.name as string).trim();

  // one drive posted under many names would fill the board (red-team 2026-09-24): a client keeps
  // to a few names per board. Checked before the replay, the costly step.
  const board = `track_id=eq.${encodeURIComponent(body.trackId as string)}&mode=eq.${mode}&daily_seed=${mode === 'daily' ? `eq.${seed}` : 'is.null'}`;
  const mine = await rest(`scores?select=name&ip_hash=eq.${ipHash}&${board}&limit=500`).catch(() => null);
  if (!mine?.ok) return json(503, { error: 'the leaderboard is busy: try again soon' });
  const names = new Set(((await mine.json()) as { name: string }[]).map((r) => r.name));
  if (!names.has(name) && names.size >= NAMES_PER_BOARD) return json(400, { error: `you already post under ${NAMES_PER_BOARD} names on this board` });

  const verdict = verifyRun(TRACKS[body.trackId as string], mode, body.racerId as string, seed, body.inputLog as string, body.timeMs as number);
  if (!verdict.ok) return json(422, { error: verdict.reason });

  const row = {
    name, track_id: body.trackId, mode, daily_seed: mode === 'daily' ? seed : null,
    speed_class: 150, racer_id: body.racerId, time_ms: verdict.timeMs, lap_times_ms: verdict.lapTimesMs,
    input_log: verdict.canonicalLog, client_version: CLIENT_VERSION, ip_hash: ipHash, verified: true,
  };
  const ins = await rest('scores?select=id,time_ms', { method: 'POST', body: JSON.stringify(row), headers: { Prefer: 'return=representation' } });
  if (ins.status === 409) return json(409, { error: 'that exact run is already on the board' });
  if (!ins.ok) {
    // the database's own count (trigger scores_names_cap): posts sent together all passed the count above
    const e = (await ins.json().catch(() => null)) as { message?: string } | null;
    if (e?.message === 'names per board') return json(400, { error: `you already post under ${NAMES_PER_BOARD} names on this board` });
    return json(500, { error: 'could not save the score' });
  }
  const [saved] = await ins.json();

  // where the name placed on its board: the board keeps each name's best run, which may be an
  // earlier one (bestId, bestMs), so look for the name, not for this run
  const top = await fetch(`${SUPABASE_URL}/rest/v1/rpc/get_leaderboard`, {
    method: 'POST', body: JSON.stringify({ p_track_id: row.track_id, p_mode: mode, p_daily_seed: row.daily_seed, p_limit: 50 }),
    headers: { apikey: ANON_KEY, Authorization: `Bearer ${ANON_KEY}`, 'Content-Type': 'application/json' },
  }).catch(() => null);
  const rows = top?.ok ? (await top.json()) as { id: string; name: string; time_ms: number }[] : [];
  const at = rows.findIndex((r) => r.name === row.name);
  return json(201, { id: saved.id, timeMs: saved.time_ms, rank: at >= 0 ? at + 1 : null, bestId: rows[at]?.id ?? null, bestMs: rows[at]?.time_ms ?? null });
});
