// submit-score: the only way a score reaches the database (docs/sops/backend-leaderboard.md).
// Order: CORS → rate limit per hashed IP → field rules → re-simulate the input log with the real
// game code → insert with the service role. The stored time is always the replay's.
// core.js is generated by `npm run build:function`; never edit it by hand.
import { CLIENT_VERSION, MAX_LOG_BYTES, TRACKS, TRACK_IDS, checkSubmission, dailySeed, verifyRun } from './core.js';

const SUPABASE_URL = Deno.env.get('SUPABASE_URL') ?? '';
const SERVICE_KEY = Deno.env.get('SUPABASE_SERVICE_ROLE_KEY') ?? '';
const LIMIT_PER_MINUTE = 10;

const CORS = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
  'Access-Control-Allow-Methods': 'POST, OPTIONS',
};

const json = (status: number, body: unknown) =>
  new Response(JSON.stringify(body), { status, headers: { ...CORS, 'Content-Type': 'application/json' } });

const rest = (path: string, init: RequestInit = {}) =>
  fetch(`${SUPABASE_URL}/rest/v1/${path}`, {
    ...init,
    headers: { apikey: SERVICE_KEY, Authorization: `Bearer ${SERVICE_KEY}`, 'Content-Type': 'application/json', ...(init.headers ?? {}) },
  });

async function sha256(text: string): Promise<string> {
  const d = await crypto.subtle.digest('SHA-256', new TextEncoder().encode(text));
  return [...new Uint8Array(d)].map((b) => b.toString(16).padStart(2, '0')).join('');
}

function clientIp(req: Request): string {
  return req.headers.get('cf-connecting-ip') ?? req.headers.get('x-real-ip') ?? req.headers.get('x-forwarded-for')?.split(',')[0]?.trim() ?? 'unknown';
}

/** Count this IP's attempts in the last minute, then record this one. True when over the limit. */
async function throttled(ipHash: string): Promise<boolean> {
  const since = new Date(Date.now() - 60_000).toISOString();
  const r = await rest(`submit_attempts?select=id&ip_hash=eq.${ipHash}&at=gte.${encodeURIComponent(since)}`, {
    method: 'HEAD', headers: { Prefer: 'count=exact', Range: '0-0' },
  });
  const count = Number(r.headers.get('content-range')?.split('/')[1] ?? '0');
  await rest('submit_attempts', { method: 'POST', body: JSON.stringify({ ip_hash: ipHash }), headers: { Prefer: 'return=minimal' } });
  // now and then, forget attempts older than a day
  if (Math.random() < 0.02) await rest(`submit_attempts?at=lt.${encodeURIComponent(new Date(Date.now() - 86_400_000).toISOString())}`, { method: 'DELETE' });
  return count >= LIMIT_PER_MINUTE;
}

Deno.serve(async (req) => {
  if (req.method === 'OPTIONS') return new Response('ok', { headers: CORS });
  if (req.method !== 'POST') return json(405, { error: 'POST only' });
  if (!SUPABASE_URL || !SERVICE_KEY) return json(500, { error: 'server not configured' });

  // salted so the stored hash cannot be reversed with a table of IPs
  const ipHash = await sha256(`${clientIp(req)}|${SERVICE_KEY.slice(-24)}`);
  if (await throttled(ipHash)) return json(429, { error: 'too many submissions: wait a minute' });

  const text = await req.text();
  if (text.length > MAX_LOG_BYTES + 4096) return json(413, { error: 'payload too large' });
  let body: Record<string, unknown>;
  try { body = JSON.parse(text); } catch { return json(400, { error: 'body must be JSON' }); }

  const problem = checkSubmission(body, TRACK_IDS, dailySeed());
  if (problem) return json(400, { error: problem });

  const mode = body.mode as 'timeTrial' | 'daily';
  const seed = mode === 'daily' ? (body.dailySeed as number) : 0;
  const verdict = verifyRun(TRACKS[body.trackId as string], mode, body.racerId as string, seed, body.inputLog as string, body.timeMs as number);
  if (!verdict.ok) return json(422, { error: verdict.reason });

  const row = {
    name: (body.name as string).trim(), track_id: body.trackId, mode, daily_seed: mode === 'daily' ? seed : null,
    speed_class: 150, racer_id: body.racerId, time_ms: verdict.timeMs, lap_times_ms: verdict.lapTimesMs,
    input_log: body.inputLog, client_version: CLIENT_VERSION, ip_hash: ipHash, verified: true,
  };
  const ins = await rest('scores?select=id,time_ms', { method: 'POST', body: JSON.stringify(row), headers: { Prefer: 'return=representation' } });
  if (!ins.ok) return json(500, { error: 'could not save the score' });
  const [saved] = await ins.json();

  // where it placed on its board (best per name, as the board shows it)
  const board = await rest('rpc/get_leaderboard', {
    method: 'POST', body: JSON.stringify({ p_track_id: row.track_id, p_mode: mode, p_daily_seed: row.daily_seed, p_limit: 50 }),
  });
  const rows = board.ok ? (await board.json()) as { id: string }[] : [];
  const rank = rows.findIndex((r) => r.id === saved.id) + 1;
  return json(201, { id: saved.id, timeMs: saved.time_ms, rank: rank > 0 ? rank : null });
});
