// submit-score: the only way a score reaches the database (docs/sops/backend-leaderboard.md).
// Order: CORS → size → atomic rate limit per hashed client (IPv6 by /64; fails closed) → field
// rules → re-simulate the input log with the real game code → insert the canonical log with the
// service role. The stored time is always the replay's; one drive is one row.
// core.js is generated by `npm run build:function`; never edit it by hand.
import { CLIENT_VERSION, MAX_LOG_BYTES, TRACKS, TRACK_IDS, checkSubmission, dailySeed, ipBucket, verifyRun } from './core.js';

const SUPABASE_URL = Deno.env.get('SUPABASE_URL') ?? '';
const SERVICE_KEY = Deno.env.get('SUPABASE_SERVICE_ROLE_KEY') ?? '';
const LIMIT_PER_MINUTE = 10;
/** accepted runs per client per day: plenty for a person, a ceiling for a flood */
const LIMIT_PER_DAY = 60;
const MAX_BODY = MAX_LOG_BYTES + 4096;

const CORS = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
  'Access-Control-Allow-Methods': 'POST, OPTIONS',
};

const json = (status: number, body: unknown) =>
  new Response(JSON.stringify(body), { status, headers: { ...CORS, 'Content-Type': 'application/json' } });

const rest = (path: string, init: RequestInit = {}) =>
  fetch(`${SUPABASE_URL}/rest/v1/${path}`, {
    ...init,
    headers: { apikey: SERVICE_KEY, Authorization: `Bearer ${SERVICE_KEY}`, 'Content-Type': 'application/json', ...(init.headers ?? {}) },
  });

async function sha256(text: string): Promise<string> {
  const d = await crypto.subtle.digest('SHA-256', new TextEncoder().encode(text));
  return [...new Uint8Array(d)].map((b) => b.toString(16).padStart(2, '0')).join('');
}

function clientIp(req: Request): string {
  return req.headers.get('cf-connecting-ip') ?? req.headers.get('x-real-ip') ?? req.headers.get('x-forwarded-for')?.split(',')[0]?.trim() ?? 'unknown';
}

/**
 * One atomic step in the database (take_submit_slot): under both limits it records this attempt
 * and says true. Null when the database could not answer: the caller then refuses (fails closed).
 */
async function takeSlot(ipHash: string): Promise<boolean | null> {
  const r = await rest('rpc/take_submit_slot', {
    method: 'POST', body: JSON.stringify({ p_ip_hash: ipHash, p_per_minute: LIMIT_PER_MINUTE, p_per_day: LIMIT_PER_DAY }),
  }).catch(() => null);
  if (!r?.ok) return null;
  return (await r.json().catch(() => null)) === true;
}

Deno.serve(async (req) => {
  if (req.method === 'OPTIONS') return new Response('ok', { headers: CORS });
  if (req.method !== 'POST') return json(405, { error: 'POST only' });
  if (!SUPABASE_URL || !SERVICE_KEY) return json(500, { error: 'server not configured' });

  // refuse an oversized body before reading it
  if (Number(req.headers.get('content-length') ?? '0') > MAX_BODY) return json(413, { error: 'payload too large' });

  // salted so the stored hash cannot be reversed with a table of IPs; IPv6 counts by its /64
  const ipHash = await sha256(`${ipBucket(clientIp(req))}|${SERVICE_KEY.slice(-24)}`);
  const slot = await takeSlot(ipHash);
  if (slot === null) return json(503, { error: 'the leaderboard is busy: try again soon' });
  if (!slot) return json(429, { error: 'too many submissions: wait a minute' });

  const text = await req.text();
  if (text.length > MAX_BODY) return json(413, { error: 'payload too large' });
  let body: Record<string, unknown>;
  try { body = JSON.parse(text); } catch { return json(400, { error: 'body must be JSON' }); }

  const problem = checkSubmission(body, TRACK_IDS, dailySeed());
  if (problem) return json(400, { error: problem });

  const mode = body.mode as 'timeTrial' | 'daily';
  const seed = mode === 'daily' ? (body.dailySeed as number) : 0;
  const verdict = verifyRun(TRACKS[body.trackId as string], mode, body.racerId as string, seed, body.inputLog as string, body.timeMs as number);
  if (!verdict.ok) return json(422, { error: verdict.reason });

  const row = {
    name: (body.name as string).trim(), track_id: body.trackId, mode, daily_seed: mode === 'daily' ? seed : null,
    speed_class: 150, racer_id: body.racerId, time_ms: verdict.timeMs, lap_times_ms: verdict.lapTimesMs,
    input_log: verdict.canonicalLog, client_version: CLIENT_VERSION, ip_hash: ipHash, verified: true,
  };
  const ins = await rest('scores?select=id,time_ms', { method: 'POST', body: JSON.stringify(row), headers: { Prefer: 'return=representation' } });
  if (ins.status === 409) return json(409, { error: 'that exact run is already on the board' });
  if (!ins.ok) return json(500, { error: 'could not save the score' });
  const [saved] = await ins.json();

  // where the name placed on its board: the board keeps each name's best run, which may be an
  // earlier one (bestId, bestMs), so look for the name, not for this run
  const board = await rest('rpc/get_leaderboard', {
    method: 'POST', body: JSON.stringify({ p_track_id: row.track_id, p_mode: mode, p_daily_seed: row.daily_seed, p_limit: 50 }),
  });
  const rows = board.ok ? (await board.json()) as { id: string; name: string; time_ms: number }[] : [];
  const at = rows.findIndex((r) => r.name === row.name);
  return json(201, { id: saved.id, timeMs: saved.time_ms, rank: at >= 0 ? at + 1 : null, bestId: rows[at]?.id ?? null, bestMs: rows[at]?.time_ms ?? null });
});
